// constants
import { CARD_TYPES } from 'boot/constants';

export const INIT_STATE = {
  allCards: [
    {
      id: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
      exp_month: 8,
      exp_year: 2023,
      last4: '4242',
      number: '4242424242424242',
      name: 'Andrea Baronchelli',
      isFreezed: false,
      currency: 'S$',
      accountBalance: 12500,
      type: CARD_TYPES.DEBIT,
    },
    {
      id: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed',
      exp_month: 8,
      exp_year: 2023,
      last4: '4242',
      number: '4242424242424242',
      name: 'Giovanni Casinelli',
      isFreezed: false,
      currency: 'S$',
      accountBalance: 22750,
      type: CARD_TYPES.DEBIT,
    },
  ],
  recentTransactions: [
    {
      transactionTo: 'Hamleys',
      transactionDescription: 'Refund on debit card',
      amount: 150,
      currency: 'S$',
      isCredit: true,
      date: '2020-05-20T13:10:16+05:30',
      category: 'Other',
    },
    {
      transactionTo: 'Food Panda',
      transactionDescription: 'Charged to debit card',
      amount: 64,
      currency: 'S$',
      isCredit: false,
      date: '2020-05-19T12:10:16+05:30',
      category: 'Food',
    },
    {
      transactionTo: 'Uber',
      transactionDescription: 'Charged to debit card',
      amount: 103,
      currency: 'S$',
      isCredit: false,
      date: '2020-05-19T11:10:16+05:30',
      category: 'Travels',
    },
    {
      transactionTo: 'Food Panda',
      transactionDescription: 'Charged to debit card',
      amount: 39,
      currency: 'S$',
      isCredit: false,
      date: '2020-05-19T12:10:16+05:30',
      category: 'Food',
    },
    {
      transactionTo: 'Indigo',
      transactionDescription: 'Charged to debit card',
      amount: 560,
      currency: 'S$',
      isCredit: false,
      date: '2020-05-19T11:10:16+05:30',
      category: 'Flight',
    },
  ],
};
